theme: jekyll-theme-minimal
title: ZigCodes' homepage
description: Solution Architect by day. Coder, builder and jack of all trades by night. Blessed with extreme curiosity but "cursed" with having to solve every puzzle.